parameters:
#    suin_interactive_shell.example.class: Suin\InteractiveShellBundle\Example

services:
#    suin_interactive_shell.example:
#        class: %suin_interactive_shell.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
